### ISSUE TITLE
The Provided Link is Not Working

### ISSUE THREAD

**Issue by s-m-quadri** [shaikhmudassir/notedown#1]
# Why?

There are several platforms, (you know it!) which provide free place for hosting. Making it alive would be helpful.

> Maybe that's not the in priority list for you, but a good idea!

**Comment by shaikhmudassir0** [comment]
It has migrated to another platform. I will update it soon

**Comment by s-m-quadri** [comment]
:+1:  **Okay! That's fine.** Close this issue, when it'll be done.
